name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      PRODUCTION_SERVER: ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install SSH client
        run: |
          sudo apt-get update -y
          sudo apt-get install openssh-client -y

      - name: Add SSH key and known hosts
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add -
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          ssh-add -l  # List loaded SSH keys for debugging

      - name: Test SSH connection
        run: |
          ssh -v $PRODUCTION_SERVER "echo 'SSH connection successful'"

      - name: Deploy to server
        run: |
          ssh $PRODUCTION_SERVER "sudo mkdir -p $DEPLOY_PATH"
          ssh $PRODUCTION_SERVER "cd $DEPLOY_PATH && git pull origin main"
          ssh $PRODUCTION_SERVER "cd $DEPLOY_PATH && composer install --no-dev"
